from tkinter import *

root = Tk() #6 i 11
root.title("Raspisanie")

a = StringVar()
a.set('')
b = StringVar()
b.set('')
c = StringVar()
c.set('')

Label(text="").grid(row=0, column=0)
table_name = Label(width=50)
table_name.grid(row=0, column=1, columnspan=3)
Label(text="").grid(row=1, column=0)
Label(text="").grid(row=3, column=0)
Label(text="").grid(row=5, column=0)
Label(text="").grid(row=7, column=0)
Label(text="").grid(row=9, column=0)
Label(text="").grid(row=11, column=0)
Label(text="Понедельник").grid(row=2, column=0)
Label(text="Вторник").grid(row=4, column=0)
Label(text="Среда").grid(row=6, column=0)
Label(text="Четверг").grid(row=8, column=0)
Label(text="Пятница").grid(row=10, column=0)
Label(text="0\n7:40-8:25").grid(row=0, column=1)
Label(text="1\n8:20-9:15").grid(row=0, column=2)
Label(text="2\n9:20-10:05").grid(row=0, column=3)
Label(text="3\n10:10-10:55").grid(row=0, column=4)
Label(text="4\n11:00-11:45").grid(row=0, column=5)
Label(text="5\n11:50-12:35").grid(row=0, column=6)
Label(text="6\n12:40-13:25").grid(row=0, column=7)
Label(text="7\n13:30-14:15").grid(row=0, column=8)
Label(text="8\n14:20-15:05").grid(row=0, column=9)
Label(text="9\n15:10-15:55").grid(row=0, column=10)
Label(text="Eesti keel", bg="grey").grid(row=1, column=2)
Label(text="Logistikateenused\nja varude juhtimine", bg="green").grid(row=1, column=3, columnspan=2)
Label(text="Matemaatika", bg="pink").grid(row=1, column=5)
Label(text="Matemaatika", bg="pink").grid(row=1, column=6)
Label(text="").grid(row=1, column=7)
Label(text="Keel ja\nkirjandus", bg="green").grid(row=1, column=8)
Label(text="Keel ja\nkirjandus", bg="green").grid(row=1, column=9)
Label(text="Tugiope\n(matemaatika)", bg="pink").grid(row=1, column=10)
Label(text="Tugiope\n(keemia)", bg="purple").grid(row=4, column=2)
Label(text="Programeerimise alused(eesti keeles)", bg="lightblue").grid(row=4, column=3, columnspan=3)
Label(text="").grid(row=4, column=6)
Label(text="Füüsika", bg="pink").grid(row=4, column=7, columnspan=2)
Label(text="").grid(row=6, column=1)
Label(text="Eesti keel\nkui teine", bg="purple").grid(row=6, column=2)

Label(text="Kunstiained\n(eesti keeles)", bg="purple").grid(row=6, column=3, columnspan=2)
Label(text="").grid(row=6, column=5)
Label(text="   Kehaline kasvatus   ", bg="purple").grid(row=6, column=6, columnspan=2)
Label(text="Logistikateenused\nja varude juhtimine", bg="green").grid(row=7, column=2,columnspan=2)
Label(text="Programeerimise alused(eesti keeles)", bg="lightblue").grid(row=7, column=5, columnspan=2)
Label(text="Inglise keel", bg="lightyellow").grid(row=7, column=7, columnspan=2)
Label(text="Arenduskeskkonna loomine", bg="pink").grid(row=8, column=7, columnspan=2)
Label(text="Eesti keel", bg="grey").grid(row=8, column=9, columnspan=7)
Label(text="Arenduskeskkonna loomine", bg="pink").grid(row=7, column=9, columnspan=2)
Label(text="Eesti keel", bg="pink").grid(row=9, column=2, columnspan=2)
Label(text="Arenduskeskkonna loomine", bg="pink").grid(row=10, column=2, columnspan=2)
Label(text="Programeerimise alused(eesti keeles)", bg="lightblue").grid(row=10, column=3, columnspan=5)
Label(text="Arenduskeskkonna loomine", bg="pink").grid(row=9, column=9, columnspan=2)
Label(text="Inglise keel", bg="green").grid(row=10, column=9, columnspan=2)
Label(text="Programeerimise alused(eesti keeles)", bg="lightblue").grid(row=10, column=5, columnspan=5)

root.mainloop()
